export type Guide = {
  slug: string
  name: string
  eyebrow: string
  summary: string
  introduction: string
  highlights: { title: string; description: string }[]
  facts: { label: string; value: string }[]
}

export const countries: Guide[] = [
  {
    slug: 'australia', name: 'Australia', eyebrow: 'Study destination',
    summary: 'A popular choice for practical, internationally recognised education and a welcoming multicultural student experience.',
    introduction: 'Australia offers foundation, vocational, undergraduate and postgraduate pathways across major student cities. Nepalese applicants should compare course outcomes, total living costs and visa requirements—not only university rankings—before choosing a programme.',
    facts: [{ label: 'Academic year', value: 'Main intakes in February and July' }, { label: 'Language', value: 'English' }, { label: 'Popular cities', value: 'Sydney, Melbourne, Brisbane, Adelaide and Perth' }],
    highlights: [{ title: 'Wide course choice', description: 'Choose from universities, pathway colleges and vocational providers.' }, { title: 'Plan the full budget', description: 'Allow for tuition, accommodation, health cover, transport and daily expenses.' }, { title: 'Check current visa rules', description: 'Entry and post-study settings change; verify them before applying.' }],
  },
  {
    slug: 'canada', name: 'Canada', eyebrow: 'Study destination',
    summary: 'Known for respected institutions, diverse communities and programmes ranging from diplomas to research degrees.',
    introduction: 'Canada has universities and colleges across provinces with different climates, costs and employment markets. Focus on the institution’s status, programme relevance and realistic funding, and confirm current study-permit and post-graduation eligibility rules before committing.',
    facts: [{ label: 'Academic year', value: 'Common intakes in September, January and May' }, { label: 'Languages', value: 'English and French' }, { label: 'Popular cities', value: 'Toronto, Vancouver, Ottawa, Calgary and Montreal' }],
    highlights: [{ title: 'University and college routes', description: 'Compare academic degrees with career-focused diploma options.' }, { title: 'Province matters', description: 'Costs, weather and opportunities vary significantly by location.' }, { title: 'Verify eligibility', description: 'Confirm programme and permit requirements on official sources.' }],
  },
  {
    slug: 'uk', name: 'United Kingdom', eyebrow: 'Study destination',
    summary: 'Home to globally recognised universities, focused degrees and many one-year taught master’s programmes.',
    introduction: 'The UK offers a large range of undergraduate, postgraduate and pathway programmes in England, Scotland, Wales and Northern Ireland. Course length can be attractive, but students should compare tuition, city living costs, entry requirements and graduate outcomes carefully.',
    facts: [{ label: 'Academic year', value: 'Main intake in September; some January options' }, { label: 'Language', value: 'English' }, { label: 'Popular cities', value: 'London, Manchester, Birmingham, Edinburgh and Glasgow' }],
    highlights: [{ title: 'Focused programmes', description: 'Many degrees specialise earlier than comparable programmes elsewhere.' }, { title: 'Shorter master’s options', description: 'A large number of taught master’s degrees take one year.' }, { title: 'Budget by city', description: 'Accommodation and transport costs vary widely across the UK.' }],
  },
  {
    slug: 'usa', name: 'United States', eyebrow: 'Study destination',
    summary: 'Offers exceptional academic variety, flexible degree structures and institutions in every type of setting.',
    introduction: 'US study options range from community colleges and liberal arts colleges to large research universities. Admissions, scholarships and testing policies differ by institution, so build a balanced shortlist based on academic fit, affordability and support for international students.',
    facts: [{ label: 'Academic year', value: 'Main intake in August or September; January also available' }, { label: 'Language', value: 'English' }, { label: 'Study options', value: 'Community colleges, colleges and universities' }],
    highlights: [{ title: 'Flexible study', description: 'Many undergraduate programmes allow exploration before declaring a major.' }, { title: 'Varied admissions', description: 'Each institution sets its own academic and testing requirements.' }, { title: 'Funding opportunities', description: 'Research scholarships early and compare the final net cost.' }],
  },
  {
    slug: 'new-zealand', name: 'New Zealand', eyebrow: 'Study destination',
    summary: 'A compact, student-friendly destination with respected qualifications and strong links to applied learning.',
    introduction: 'New Zealand’s universities and institutes offer programmes in welcoming cities with easy access to nature. Students should evaluate programme accreditation, living costs, insurance and current immigration requirements before making an application.',
    facts: [{ label: 'Academic year', value: 'Common intakes in February and July' }, { label: 'Language', value: 'English' }, { label: 'Popular cities', value: 'Auckland, Wellington, Christchurch and Dunedin' }],
    highlights: [{ title: 'Recognised education', description: 'Qualifications span undergraduate, postgraduate and applied pathways.' }, { title: 'Smaller study destination', description: 'A compact system can make comparing institutions more manageable.' }, { title: 'Prepare early', description: 'Plan finances, accommodation and visa evidence well ahead of intake.' }],
  },
]

export const tests: Guide[] = [
  { slug: 'ielts', name: 'IELTS', eyebrow: 'Test preparation', summary: 'Build confidence across Listening, Reading, Writing and Speaking for academic admission and migration purposes.', introduction: 'IELTS preparation works best when you first identify your required band score and test format. Combine timed practice with targeted feedback, especially for Writing and Speaking, and use official-style materials to become comfortable with the question types.', facts: [{ label: 'Skills tested', value: 'Listening, Reading, Writing and Speaking' }, { label: 'Formats', value: 'Academic and General Training' }, { label: 'Best first step', value: 'Take a diagnostic test' }], highlights: [{ title: 'Know your target', description: 'Confirm the overall and individual band scores your institution requires.' }, { title: 'Practise to time', description: 'Build accuracy first, then complete full sections under test conditions.' }, { title: 'Get feedback', description: 'Expert review helps uncover recurring Writing and Speaking weaknesses.' }] },
  { slug: 'pte', name: 'PTE Academic', eyebrow: 'Test preparation', summary: 'Prepare for a computer-based English test that assesses integrated communication skills.', introduction: 'PTE Academic rewards clear communication, familiarity with the test interface and consistent performance across integrated tasks. Start with a scored diagnostic, learn how each task contributes to skill scores, and practise speaking naturally into a microphone.', facts: [{ label: 'Delivery', value: 'Computer based' }, { label: 'Skills tested', value: 'Speaking, Writing, Reading and Listening' }, { label: 'Best first step', value: 'Learn the task formats' }], highlights: [{ title: 'Understand scoring', description: 'Prioritise tasks using official scoring information, not shortcuts.' }, { title: 'Speak clearly', description: 'Practise steady pacing, pronunciation and microphone technique.' }, { title: 'Review mistakes', description: 'Track repeated grammar, vocabulary and comprehension errors.' }] },
  { slug: 'toefl', name: 'TOEFL iBT', eyebrow: 'Test preparation', summary: 'Develop the academic English skills needed to communicate in a university environment.', introduction: 'TOEFL iBT focuses on using English in academic contexts, including tasks that combine reading, listening, speaking and writing. Build note-taking and synthesis skills alongside language accuracy, then use full timed practice to develop stamina.', facts: [{ label: 'Delivery', value: 'Internet based' }, { label: 'Focus', value: 'Academic English' }, { label: 'Best first step', value: 'Confirm your required score' }], highlights: [{ title: 'Integrated tasks', description: 'Practise combining information from reading and listening sources.' }, { title: 'Academic vocabulary', description: 'Learn words in context rather than memorising isolated lists.' }, { title: 'Timed responses', description: 'Use simple response structures you can execute under pressure.' }] },
  { slug: 'sat', name: 'SAT', eyebrow: 'Test preparation', summary: 'Strengthen Reading and Writing and Math skills for undergraduate admission where the SAT is considered.', introduction: 'Effective SAT preparation starts with checking whether your target institutions require or consider the test. Use a diagnostic to find content gaps, practise with the digital testing tools and review why every missed answer was wrong.', facts: [{ label: 'Sections', value: 'Reading and Writing, and Math' }, { label: 'Delivery', value: 'Digital' }, { label: 'Best first step', value: 'Check university testing policies' }], highlights: [{ title: 'Close content gaps', description: 'Review core grammar, algebra, problem solving and data analysis.' }, { title: 'Use official practice', description: 'Become familiar with the digital format and built-in tools.' }, { title: 'Analyse every error', description: 'Separate knowledge gaps from timing and interpretation mistakes.' }] },
]

export const locations: Guide[] = [
  { slug: 'kathmandu', name: 'Kathmandu', eyebrow: 'Consultancy location', summary: 'Explore education consultancies and study-abroad support in Nepal’s largest student services hub.', introduction: 'Kathmandu has Nepal’s widest concentration of education consultancies, language-test centres and application support services. Compare counsellor experience, university partnerships, fee transparency and after-enrolment support before choosing an office.', facts: [{ label: 'Area', value: 'Bagmati Province' }, { label: 'Common hubs', value: 'Putalisadak, New Baneshwor and Dillibazar' }, { label: 'Services', value: 'Counselling, applications, test prep and visa guidance' }], highlights: [{ title: 'Compare several offices', description: 'Ask each consultancy for a written breakdown of services and charges.' }, { title: 'Verify claims', description: 'Confirm institutional partnerships and admissions advice independently.' }, { title: 'Keep your documents', description: 'Retain access to your email, applications, receipts and original records.' }] },
  { slug: 'pokhara', name: 'Pokhara', eyebrow: 'Consultancy location', summary: 'Find local counselling and test-preparation support without travelling to Kathmandu.', introduction: 'Pokhara offers a growing choice of education consultancies and language-test preparation providers. Look for advisers with experience in your destination and course, transparent processes and convenient access for follow-up appointments.', facts: [{ label: 'Area', value: 'Gandaki Province' }, { label: 'Common hubs', value: 'New Road, Chipledhunga and Mahendrapul' }, { label: 'Services', value: 'Counselling, applications and test preparation' }], highlights: [{ title: 'Ask about expertise', description: 'Choose advisers familiar with your intended country and study level.' }, { title: 'Review the service agreement', description: 'Understand inclusions, refunds and third-party charges before paying.' }, { title: 'Check student support', description: 'Ask what help continues after you receive an offer or visa.' }] },
  { slug: 'chitwan', name: 'Chitwan', eyebrow: 'Consultancy location', summary: 'Compare accessible study-abroad guidance and preparation services in central Nepal.', introduction: 'Consultancies around Bharatpur and Narayangarh provide counselling, test preparation and application assistance for major study destinations. Evaluate the quality of the individual counsellor and documentation process rather than relying only on brand recognition.', facts: [{ label: 'Area', value: 'Bagmati Province' }, { label: 'Common hubs', value: 'Bharatpur and Narayangarh' }, { label: 'Services', value: 'Counselling, test prep and application guidance' }], highlights: [{ title: 'Meet your counsellor', description: 'Ask who will manage your case and how frequently you can get updates.' }, { title: 'Demand transparency', description: 'Get realistic information about costs, timelines and admission chances.' }, { title: 'Use official sources', description: 'Cross-check important visa and institution details before decisions.' }] },
  { slug: 'butwal', name: 'Butwal', eyebrow: 'Consultancy location', summary: 'Discover education advisers and test-prep providers serving students in Lumbini Province.', introduction: 'Butwal’s education-services market gives students in western Nepal local access to destination counselling and application support. Compare verified experience, communication standards and the total cost of services before selecting a provider.', facts: [{ label: 'Area', value: 'Lumbini Province' }, { label: 'Common hub', value: 'Butwal city centre' }, { label: 'Services', value: 'Counselling, applications and language-test preparation' }], highlights: [{ title: 'Compare advice', description: 'A second opinion can reveal more suitable courses or institutions.' }, { title: 'Understand all costs', description: 'Separate consultancy fees from university and official application fees.' }, { title: 'Protect your access', description: 'Use your own contact details and keep copies of every submission.' }] },
]

export function findGuide(guides: Guide[], slug: string) {
  return guides.find((guide) => guide.slug === slug)
}
